### ISSUE TITLE
Unhelpful error messages when Phidget board isn't connected

### ISSUE THREAD

**Issue by duncan-bayne** [duncan-bayne/arghspec#1]
Currently, arghspec fails unhelpfully when it can't talk to the Phidget board:

```
Coverage report generated for RSpec to /home/duncan/code/toy-robot/coverage. 243 / 245 LOC (99.18%) covered.
/home/duncan/.rvm/gems/ruby-2.3.0/gems/phidgets-ffi-0.1.3/lib/phidgets-ffi/ffi/common.rb:59:in `method_missing': Given timeout has been exceeded. (Phidgets::Error::Timeout)
        from /home/duncan/.rvm/gems/ruby-2.3.0/gems/phidgets-ffi-0.1.3/lib/phidgets-ffi/common.rb:279:in `wait_for_attachment'
        from /home/duncan/.rvm/gems/ruby-2.3.0/gems/phidgets-ffi-0.1.3/lib/phidgets-ffi/common.rb:175:in `initialize'
        from /home/duncan/code/arghspec/lib/arghspec/electro_formatter.rb:28:in `new'
```

If this thing ever actually has real users, then maybe fix this :smile:

**Comment by duncan-bayne** [comment]
Closing; switched to GitLab.
